// Generated by CoffeeScript 1.9.3
(function() {
  var app, bodyParser, cookieParser, express, favicon, getHandler, getRequestHandler, logger, path, postHandler, postRequestHandler;

  express = require('express');

  path = require('path');

  favicon = require('serve-favicon');

  logger = require('morgan');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  getHandler = require('./routes/getHandler');

  postHandler = require('./routes/postHandler');

  getRequestHandler = getHandler.prototype;

  postRequestHandler = postHandler.prototype;

  app = express();

  app.set('views', path.join(__dirname, '../views'));

  app.set('view engine', 'jade');

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  app.use(cookieParser());

  app.use(express["static"](path.join(__dirname, 'public')));

  app.use(function(req, res, next) {
    if (req.method === 'GET') {
      getRequestHandler.handleRequest(req, res, next);
    } else if (req.method === 'POST') {
      postRequestHandler.handleRequest(req, res, next);
    }
  });

  if (app.get('env') === 'development') {
    app.use(function(err, req, res, next) {
      res.status(err.status || 500);
      res.render('error', {
        message: err.message,
        error: err
      });
    });
  }

  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
      message: err.message,
      error: {}
    });
  });

  module.exports = app;

}).call(this);
