// Generated by CoffeeScript 1.9.3
(function() {
  var brunchSettings, exports;

  brunchSettings = exports = module.exports = {};

  brunchSettings.config = {
    modules: {
      definition: false,
      wrapper: false
    },
    sourceMaps: true,
    files: {
      javascripts: {
        defaultExtension: 'coffee',
        joinTo: {
          'javascripts/app.js': /^app/,
          'javascripts/vendor.js': /^(vendor|bower_components)/
        },
        order: {
          before: ['app/**/*module.coffee', 'app/**/*config.coffee'],
          after: ['vendor/plugins/datatables/dataTables.colVis.min.js', 'vendor/plugins/datatables/dataTables.bootstrap.js', 'vendor/plugins/datatables/dataTables.responsive.min.js']
        }
      },
      templates: {
        defaultExtension: 'hbs',
        joinTo: 'javascripts/app.js'
      }
    },
    conventions: {
      ignored: /^(vendor\/styles\/smartadmin\/)/
    },
    plugins: {
      coffeelint: {
        pattern: /^app\/.*\.coffee$/,
        options: {
          max_line_length: {
            level: "ignore"
          },
          indentation: {
            value: 2,
            level: "error"
          }
        }
      }
    },
    server: {
      path: 'server.coffee',
      port: 3000
    }
  };

}).call(this);
