// Generated by CoffeeScript 1.9.3
(function() {
  var GetHandler, fs;

  fs = require('fs');

  GetHandler = function() {};


  /* Handle Incoming GET Requests */

  GetHandler.prototype.handleRequest = function(req, res, next) {
    fs.readFile('/data/json' + req.originalUrl + '/info.json', 'utf8', function(err, data) {
      if (err) {
        next(err);
      } else {
        res.json(JSON.parse(data));
        next();
      }
    });
  };

  module.exports = GetHandler;

}).call(this);
