// Generated by CoffeeScript 1.9.3
(function() {
  var PostHandler, fs, getParamValue;

  fs = require('fs');

  PostHandler = function() {};

  getParamValue = function(parameter, inputParameters) {
    if (inputParameters.hasOwnProperty(parameter)) {
      return inputParameters[parameter];
    }
  };


  /* Handle Incoming GET Requests */

  PostHandler.prototype.handleRequest = function(req, res, next) {
    var arrayFound, executablePath, fileContent, inputParameters, neededParameters, parameter, value;
    fileContent = JSON.parse(fs.readFileSync('/data/json/services.json', 'utf8'));
    arrayFound = fileContent.services.filter(function(item) {
      return item.path === req.originalUrl;
    });
    if (typeof arrayFound !== 'undefined') {
      console.log(req.body);
      neededParameters = arrayFound[0].parameters;
      inputParameters = req.body.inputs;
      executablePath = arrayFound[0].executablePath;
      for (parameter in neededParameters) {
        value = getParamValue(parameter, inputParameters);
        if (typeof value !== 'undefined') {
          executablePath += ' ' + value;
        }
      }
      console.log(executablePath);
      res.sendStatus(200);
    }
    next();
  };

  module.exports = PostHandler;

}).call(this);
